[[redirects]]
 from = "/nginx/:match*"
 to = "https://romantic-visvesvaraya-39e8bf.netlify.app/nginx/:match*"
 status = 200
 force = true


[build]
  command = "npm run build && npm run export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"