[[redirects]]
from = "/google"
to = "https://www.google.com"
status = 301
force = false

[[redirects]]
from = "/nginx/*"
to = "https://romantic-visvesvaraya-39e8bf.netlify.app/nginx/:splat"
status = 200
force = true